---
- name: learn conditionals
  hosts: web
  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: install packages
    apt:
      name: apache2
      state: present
    loop: "{{ansible_mounts}}"
    when: item.mount == "/" and item.size_available > 3000000 and item.fstype == "ext4"
  - name: enable service
    service:
      name: apache2
      enabled: true
      state: started
  - name: create index.html file
    blockinfile:
      path: /var/www/html/index.html
      create: true
      block: |
             Hello friends, learning ansible is a fun.
             we will use similar commands to install dockers